on: [ push, pull_request ]

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check dependencies with PyUp
        run: |
          pip install -r requirements.txt
          pip install safety
          safety check

      - name: Check dependencies with Ochrona
        run: |
          pip install ochrona
          ochrona --file requirements.txt
